repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.8.4
  hooks:
    # Run the linter.
    - id: ruff
      name: lint with ruff
    - id: ruff
      name: sort imports with ruff
      args: [--select, I, --fix]
    # Run the formatter.
    - id: ruff-format
      name: format with ruff